name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-code:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install xvfb
        run: sudo apt-get install xvfb


      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Print ChromeDriver and Chrome versions
        run: |
          chromedriver --version
          google-chrome-stable --version

      - name: Execute tests
        run: |
          export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}
          pytest ./tests/code/
